// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDffumN8kBlu2M5zZo62cFEVd5zHm-S1f4',
    appId: '1:234179407636:web:4ad0f524d2a5e47e685c01',
    messagingSenderId: '234179407636',
    projectId: 'fir-intro-8fbed',
    authDomain: 'fir-intro-8fbed.firebaseapp.com',
    storageBucket: 'fir-intro-8fbed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0AWtux2uF2Z2S-nRm48vvqVCHKvqTh9U',
    appId: '1:234179407636:android:f3b3cf0554ea8814685c01',
    messagingSenderId: '234179407636',
    projectId: 'fir-intro-8fbed',
    storageBucket: 'fir-intro-8fbed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEm_gcYdCyHzFmeHt4_MBgeVoqwKYFEOw',
    appId: '1:234179407636:ios:c5776a86a1f11a4e685c01',
    messagingSenderId: '234179407636',
    projectId: 'fir-intro-8fbed',
    storageBucket: 'fir-intro-8fbed.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIntro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEm_gcYdCyHzFmeHt4_MBgeVoqwKYFEOw',
    appId: '1:234179407636:ios:c5776a86a1f11a4e685c01',
    messagingSenderId: '234179407636',
    projectId: 'fir-intro-8fbed',
    storageBucket: 'fir-intro-8fbed.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIntro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDffumN8kBlu2M5zZo62cFEVd5zHm-S1f4',
    appId: '1:234179407636:web:45ea1100289acab2685c01',
    messagingSenderId: '234179407636',
    projectId: 'fir-intro-8fbed',
    authDomain: 'fir-intro-8fbed.firebaseapp.com',
    storageBucket: 'fir-intro-8fbed.firebasestorage.app',
  );

}